service: Go-Serverless-Demo

package:
  artifact: /Users/user/go/src/sless/handler.zip

provider:
  name: aws
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  runtime: python2.7
  region: us-east-1
  memorySize: 512
  deploymentBucket:
    serverSideEncryption: AES256 # Enable encryption on S3 bucket
  versionFunctions: false
  stackTags:
    key: value

custom:
  defaultStage: dev
  profiles:
    dev: default
    prod: prodProfile

functions:
  hello:
    handler: handler.Handle
    tags:
      key: value
    events:
      - http:
          path: hello
          method: get
          cors: true
